### ISSUE TITLE
Inconsistency in image_path naming convention

### ISSUE THREAD

**Issue by Mulinho** [mobiledgex/deploy-app-action#2]
Action accepts `image_path` parameter with `image` and `path` separated by `_`. Whereas, in the YAML files retrieved using the mcctl tool this parameter is  `imagepath` (without the underscore). 
The same may apply to the `imagetype`.
Consider accepting both in https://github.com/mobiledgex/deploy-app-action/blob/master/deploy-app.py,

**Comment by venkytv** [comment]
Thanks, Mulinho! This change will be included in release v1.2.2.
